<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-01T00:18:24 IST" name="Default suite" finished-at="2024-08-01T00:18:30 IST" duration-ms="6294">
    <groups>
    </groups>
    <test started-at="2024-08-01T00:18:24 IST" name="Default test" finished-at="2024-08-01T00:18:30 IST" duration-ms="6294">
      <class name="testCases.TestLoggingInWithRandomCreds">
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:testCases.TestLoggingInWithRandomCreds@743cb8e0]" started-at="2024-08-01T00:18:24 IST" name="launchBrowser" finished-at="2024-08-01T00:18:26 IST" duration-ms="1560" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method is-config="true" signature="navigateToURl()[pri:0, instance:testCases.TestLoggingInWithRandomCreds@743cb8e0]" started-at="2024-08-01T00:18:26 IST" name="navigateToURl" finished-at="2024-08-01T00:18:29 IST" duration-ms="3108" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToURl -->
        <test-method signature="loginAsRandomUser()[pri:0, instance:testCases.TestLoggingInWithRandomCreds@743cb8e0]" started-at="2024-08-01T00:18:29 IST" name="loginAsRandomUser" finished-at="2024-08-01T00:18:30 IST" duration-ms="1132" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAsRandomUser -->
        <test-method is-config="true" signature="navigateToURl()[pri:0, instance:testCases.TestLoggingInWithRandomCreds@743cb8e0]" started-at="2024-08-01T00:18:30 IST" name="navigateToURl" finished-at="2024-08-01T00:18:30 IST" duration-ms="370" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToURl -->
        <test-method signature="verifyLogin()[pri:0, instance:testCases.TestLoggingInWithRandomCreds@743cb8e0]" started-at="2024-08-01T00:18:30 IST" name="verifyLogin" finished-at="2024-08-01T00:18:30 IST" depends-on-methods="testCases.TestLoggingInWithRandomCreds.loginAsRandomUser" duration-ms="9" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<https://opensource-demo.orangehrmlive.com/web/index.php/auth/login> but was:<https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<https://opensource-demo.orangehrmlive.com/web/index.php/auth/login> but was:<https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at testCases.TestLoggingInWithRandomCreds.verifyLogin(TestLoggingInWithRandomCreds.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:testCases.TestLoggingInWithRandomCreds@743cb8e0]" started-at="2024-08-01T00:18:30 IST" name="quitBrowser" finished-at="2024-08-01T00:18:30 IST" duration-ms="90" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
      </class> <!-- testCases.TestLoggingInWithRandomCreds -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
